services:
  lotr_api:
    build: ./src/lotr_api
    container_name: lotr_api
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data

  lotr_app:
    build: ./src/lotr_app
    container_name: lotr_app
    ports:
      - "3001:3001"
    depends_on:
      - lotr_api

networks:
  default:
    driver: bridge